### ISSUE TITLE
cmd+v pastes multiple times

### ISSUE THREAD

**Issue by simonhambly** [tekkub/cut-line#11]
I'm using v0.8.0.

Cutting and pasting lines works normally, but if I cut and paste a line (in atom.io) and the copy from external app (in this case chrome) when I hit cmd+v  the clipboard is pasted twice.

further to this I copy and paste from other apps or a selection then I see the pasted content being repeated 2, 3 or even 4 times...

disabling, re-enabling the plugin resets the paste repetition to 2.

**Comment by haggen** [comment]
I just copied some text inside Atom, and when I pasted it, it appeared multiple times.

And it's like the 3rd consecutive update with major issues. I used to be happy about this plugin, but now I'm getting sad. :(

**Comment by tekkub** [comment]
Hey guys, I'm on Atom 0.101.0 and cut-line 0.8.0... and I can't seem to reproduce this.  Are you still hitting issues?

**Comment by haggen** [comment]
It haven't happened to me a while now, I think it's ok.

**Comment by tekkub** [comment]
I'm going to close this out then.  If you run into it again, please reopen this issue.

**Comment by simonhambly** [comment]
I can't reproduce it either.

**Comment by deiga** [comment]
This just started for me again.
