### ISSUE TITLE
cmd+v replaces line not inserting

### ISSUE THREAD

**Issue by simonhambly** [tekkub/cut-line#12]
Just noticed on Atom 0.101.0 and cut-line 0.8.0 that cmd+c cuts the line ok but cmd+v now replaces the line instead of inserting the line.

**Comment by tekkub** [comment]
I'm not able to produce any odd behaviour.  Can you give me more detailed step-by-step instructions to reproduce?

**Comment by simonhambly** [comment]
All I did was open up atom, open a new file and type:

```
one
two
three
four
```

moved to line with "two" on and hit cmd+c.  Then moved to the line with "three" n and hit cmd+v and this is what I ended up with:

```
one
two
two
four
```

**Comment by simonhambly** [comment]
Interestingly replaying (with cmd+z/cmd+shift+z) to do the undo/redo it does this:

I've used cmd+z to undo the changes, so start with, 

```
one
two
three
four
```

now if I hit cmd+shift+z, i get:

```
one
two

three
four
```

then hit cmd+shift+z again, I get:

```
one
two

four
```

then hit cmd+shift+z a final time, I get:

```
one
two
two
four
```

hope that helps

**Comment by tekkub** [comment]
Ah thanks, I was able to reproduce.  It looks like it's specific to pasting on an unindented line.

A fix will be going out soonly. :bear: :paw_prints:
