### ISSUE TITLE
Cutting removes two lines

### ISSUE THREAD

**Issue by jshcrowthe** [tekkub/cut-line#13]
I just updated to 0.9.0 and am having some issues of the plugin cutting two lines when I cut.

I am also if I copy then paste will have two copies of the line in my clipboard. Any thoughts?

**Comment by tekkub** [comment]
I've not run into that issue, can you give me steps to consistently reproduce it?

**Comment by jshcrowthe** [comment]
Sure I will screencast it tonight. Thanks for the quick response!

**Comment by Mx-Glitter** [comment]
I had the same problem, I removed and reinstalled the package and it worked accordingly after that.

One thing I noticed that in the package settings before, I had the keybindings weirdly repeated like this:
![atom-cut-line-keybindings](https://cloud.githubusercontent.com/assets/4671739/3396120/39230c88-fd09-11e3-93ba-ae8331c4ddae.jpg)

After reinstallation, that was gone. Hope it helps.

**Comment by jshcrowthe** [comment]
Interestingly enough after a little further investigation I have the same keymapping issues. I went in and commented out the platform-linux and platform-win32 keymaps and my problem went away. 

![screen shot 2014-06-26 at 8 20 49 am](https://cloud.githubusercontent.com/assets/5588878/3399553/190da9ec-fd3d-11e3-9fa6-34803ea35490.png)

Thanks for the help @Triiistan!
