### ISSUE TITLE
Adds extra EOL in files with \r\n EOL

### ISSUE THREAD

**Issue by vorou** [tekkub/cut-line#14]
Both copy-pasting and cut-pasting results in an extra EOL if file is using Windows line endings.

Example:

```
first
second
third
```

If I cut first, move cursor to third and paste:

```
second
first

third
```

Works fine with Unix EOLs.

**Comment by tekkub** [comment]
The lines pertaining to lineendings are [here](https://github.com/tekkub/cut-line/blob/10bc85f45ee6f13816f6b45d207d80ef8660ce79/lib/cut-line.coffee#L33) and [here](https://github.com/tekkub/cut-line/blob/10bc85f45ee6f13816f6b45d207d80ef8660ce79/lib/cut-line.coffee#L40).  Can you try replacing those with `"\r\n"` and see if that works?

**Comment by vorou** [comment]
Yep, it works. I hacked up a PR https://github.com/tekkub/cut-line/pull/15

**Comment by tekkub** [comment]
Fixed in #15
