### ISSUE TITLE
Copy & paste inserts in middle of current line instead of creating a new line

### ISSUE THREAD

**Issue by jamischarles** [tekkub/cut-line#2]
Love it,

In Sublime I frequently used copy paste and it would automatically duplicate the new content to the line below.

Can we duplicate that functionality here?

What's currently happening is that pasting will paste it in the middle of the line.

**Comment by tekkub** [comment]
I think the problem is that Atom isn't catching that the content being pasted has a newline at the end, and thus just does the usual "just shove it where the cursor is" behaviour.  I wonder if there are any events that fire upon paste which we could monitor or hook?

**Comment by jdiamond** [comment]
If there are no events, maybe override cmd-v?

**Comment by tekkub** [comment]
Overriding cmd-v is turning out to be quite not fun.  I think we should probably escalate this to atom-core, as there are other similar issues, like copy/pasting with multiple cursors doesn't behave as expected.

**Comment by tekkub** [comment]
I think all of these issues have now been resolved.  Please reopen if you run into these anywhere.
