### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by tcarlsen** [tekkub/cut-line#27]

**Comment by k4nar** [comment]
Seems to be :/ . I wonder if there is any alternative.

**Comment by tcarlsen** [comment]
I did a fork and updated the package, and released it under the name [cut-line-2](https://github.com/tcarlsen/atom-cut-line-2)

**Comment by k4nar** [comment]
Awesome, thanks!

**Comment by tcarlsen** [comment]
this feature is and has been for a long time the native behavior in atom
