### ISSUE TITLE
Selections on a line now cut entire line anyway

### ISSUE THREAD

**Issue by kreeger** [tekkub/cut-line#6]
So I've got a selection of part of a line, and a <kbd>⌘</kbd>-<kbd>X</kbd> will now cut the entire line, regardless of if I have a selection. When I undo, it puts the line _back_, at the state it _should have been_, with just the selection cut from the area. One more undo puts it back to the state it was in before I struck <kbd>⌘</kbd>-<kbd>X</kbd>.

I'd expect cut-line to not cut the entire line if I've already got a selection.

Additionally, nothing ever gets copied to the clipboard.

This just started as of the most recent update (v0.6.0).

![cut-line-bug](https://cloud.githubusercontent.com/assets/58783/2689825/cdf51460-c31f-11e3-8832-dfc08ad80041.gif)

**Comment by tekkub** [comment]
What version of atom are you on, and do you have any other plugins installed?  I've not run into this myself, currently on atom 0.85.0 (yea I need to update...)

**Comment by kreeger** [comment]
@tekkub I always keep on the latest version of Atom but it's been a while since I had this plugin last enabled. Lemme get back to you on it.
